# Generated by Django 6.0.3 on 2026-03-28 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("job_app", "0002_alter_job_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicant_name", models.CharField(max_length=255)),
                ("applicant_email", models.EmailField(max_length=254)),
                (
                    "applicant_status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("in_review", "In Review"),
                            ("interviewing", "Interviewing"),
                            ("on_hold", "On Hold"),
                            ("hired", "Hired"),
                            ("joined", "Joined"),
                        ],
                        default="applied",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        db_column="job_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="job_app.job",
                    ),
                ),
            ],
            options={
                "db_table": "applications",
            },
        ),
    ]
