# Generated by Django 6.0.3 on 2026-03-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
