# Generated by Django 6.0.3 on 2026-03-25 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job',
            table='jobs',
        ),
    ]
